name: Release
on:
  push:
    tags:
      - "**"
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: contains(github.ref, 'alpha') || contains(github.ref, 'beta')
  release:
    name: Publish release assets
    needs: create_release
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: dotnet-bump.exe
            asset_name: dotnet-bump-windows-x64
          - os: ubuntu-latest
            artifact_name: dotnet-bump
            asset_name: dotnet-bump-linux-x64
          - os: macos-latest
            artifact_name: dotnet-bump
            asset_name: dotnet-bump-macos-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish --configuration Release --no-build -p:PublishSingleFile=true -o ./dist
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
